const TILE_SIZE = 48;

const MAP_TILES_HEIGHT = 40;
const MAP_TILES_WIDTH = 70;

const MAP_HEIGHT = MAP_TILES_HEIGHT * TILE_SIZE;
const MAP_WIDTH = MAP_TILES_WIDTH * TILE_SIZE;

export { MAP_TILES_HEIGHT, MAP_TILES_WIDTH, MAP_HEIGHT, MAP_WIDTH, TILE_SIZE };
