const PLAYER_SPRITE_WIDTH = 48;
const PLAYER_SPRITE_HEIGHT = 68;
const PLAYER_SPRITES_COUNT = 4;
const PLAYER_COLLISION_RADIUS = 22;
const PLAYER_VELOCITY = 0.35;

export {
  PLAYER_SPRITE_WIDTH,
  PLAYER_SPRITE_HEIGHT,
  PLAYER_VELOCITY,
  PLAYER_SPRITES_COUNT,
  PLAYER_COLLISION_RADIUS,
};
